%% Transcriptomic E:I surface maps in Schaefer-1000
%
% This script reads the parcel values generated by build_ei_sch1000.py and
% reuses the manuscript's Schaefer-1000 surface renderer. It produces the
% same lateral, medial, and flat views for the raw and normalized E:I maps.
%
% The render_assets variable below identifies the directory containing the
% Schaefer-1000 left/right label GIFTIs and the 32k fs_LR surface GIFTIs.

clear all; close all; clc;

sch1000_root = fileparts(fileparts(fileparts(mfilename('fullpath'))));
addpath(sch1000_root, '-begin');
P = setup_sch1000_paths();

fprintf('Repository root: %s\n', P.repository_root);
assert(exist('gifti', 'file') ~= 0, ...
    ['The MATLAB GIFTI reader is not on the path. Add SPM or the GIFTI ' ...
     'toolbox before running this renderer.']);

% Surface-data directory supplied by the shared Schaefer-1000 path setup.
% If the GIFTI assets are stored elsewhere, replace P.render_assets in
% pipeline_paths.m with that directory's absolute path.
render_assets = P.render_assets;

ei_dir = fullfile(P.repository_root, 'abagen_analysis', 'abagen-code', ...
    'ei_maps', 'schaefer1000_2mm');
ei_file = fullfile(ei_dir, 'EI_values_sch1000.csv');
output_dir = fullfile(ei_dir, 'figures', 'surface_matlab');

assert(isfile(ei_file), ...
    'Missing E:I parcel table. Run build_ei_sch1000.py first: %s', ei_file);
if ~isfolder(output_dir)
    mkdir(output_dir);
end

T = readtable(ei_file);
required_columns = {'label', 'ei_raw', 'ei_minmax'};
assert(all(ismember(required_columns, T.Properties.VariableNames)), ...
    'E:I table must contain columns: %s.', strjoin(required_columns, ', '));
assert(height(T) == 1000, ...
    'Expected 1,000 Schaefer parcels; found %d.', height(T));

labels = T.label(:);
ei_raw = T.ei_raw(:);
ei_minmax = T.ei_minmax(:);
assert(isequal(labels, (1:1000)'), ...
    'Parcel labels must be unique integers ordered from 1 through 1000.');
assert(all(isfinite(ei_raw)) && all(isfinite(ei_minmax)), ...
    'E:I values must all be finite.');
assert(all(ei_minmax >= -eps & ei_minmax <= 1 + eps), ...
    'Min-max E:I values must lie within [0, 1].');

expected_minmax = (ei_raw - min(ei_raw)) ./ (max(ei_raw) - min(ei_raw));
assert(max(abs(ei_minmax - expected_minmax)) < 1e-10, ...
    'ei_minmax is not the expected min-max transform of ei_raw.');

raw_limits = [min(ei_raw), max(ei_raw)];
minmax_limits = [0, 1];
surface_type = 2;          % inflated surface; matches the renderer default
flip_colormap = 0;         % yellow (low) through orange to red (high)
colormap_name = 'YlOrRd9';
neutral_lowest = false;    % every E:I parcel is a valid continuous value

fprintf('Raw E:I range: %.6f to %.6f\n', raw_limits(1), raw_limits(2));
fprintf('Min-max E:I range: %.6f to %.6f\n', ...
    min(ei_minmax), max(ei_minmax));

raw_figure = rendersurface_schaefer1000( ...
    ei_raw, raw_limits(1), raw_limits(2), flip_colormap, ...
    colormap_name, surface_type, neutral_lowest, '%.3f', render_assets);
set(raw_figure, 'Color', 'w');
sgtitle(raw_figure, 'Raw transcriptomic E:I ratio', ...
    'FontWeight', 'bold', 'FontSize', 16);
raw_stem = fullfile(output_dir, 'EI_expression_raw_sch1000_surface');
print(raw_figure, [raw_stem '.png'], '-dpng', '-r300');
print(raw_figure, [raw_stem '.pdf'], '-dpdf', '-r300', '-bestfit');
savefig(raw_figure, [raw_stem '.fig']);

minmax_figure = rendersurface_schaefer1000( ...
    ei_minmax, minmax_limits(1), minmax_limits(2), flip_colormap, ...
    colormap_name, surface_type, neutral_lowest, '%.2f', render_assets);
set(minmax_figure, 'Color', 'w');
sgtitle(minmax_figure, 'Min-max-normalized transcriptomic E:I ratio', ...
    'FontWeight', 'bold', 'FontSize', 16);
minmax_stem = fullfile(output_dir, ...
    'EI_expression_minmax_sch1000_surface');
print(minmax_figure, [minmax_stem '.png'], '-dpng', '-r300');
print(minmax_figure, [minmax_stem '.pdf'], '-dpdf', '-r300', '-bestfit');
savefig(minmax_figure, [minmax_stem '.fig']);

metadata_file = fullfile(output_dir, 'EI_surface_render_inputs.mat');
save(metadata_file, 'labels', 'ei_raw', 'ei_minmax', 'raw_limits', ...
    'minmax_limits', 'surface_type', 'flip_colormap', 'colormap_name', ...
    'neutral_lowest', 'render_assets', 'ei_file');

fprintf('Saved E:I surface renderings to: %s\n', output_dir);
fprintf('Saved rendering inputs and provenance: %s\n', metadata_file);
